<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    use HasFactory;

    protected $table = 'pembayaran';

    protected $fillable = [
        'id_spp', 'id_user', 'pembayaran_code', 'dibayar',
        'nisn', 'spp_bulan', 'jumlah_bayar', 'sisa_bayar', 'catatan'
    ];

    public function siswa()
    {
        return $this->belongsTo(Siswa::class, 'nisn', 'nisn');
    }

    public function spp()
    {
        return $this->belongsTo(Spp::class, 'id_spp');
    }

    public function bulans()
    {
        return $this->hasMany(PembayaranBulan::class, 'id_pembayaran');
    }

    public static function generateCode()
    {
        $now = Carbon::now();
        $array = Pembayaran::latest()->first();

        $number = $array ? substr($array->id, -4) + 1 : 0001;

        return 'SPP-' . $now->isoFormat('YYYY') . $now->isoFormat('MM') . '-' . sprintf('%04d', $number);
    }

    public function getJumlahIdrAttribute()
    {
        return 'RP. ' . format_idr($this->jumlah_bayar);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
